version: '3.3'
services:
  backend:
    build: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_USERNAME: 'root'
      DB_PASSWORD: 'bank123'
      DB_DATABASE: 'bank'
      DB_PORT: '3306'
      DB_HOST: 'mysql'
    volumes:
      - '.:/app-bank'
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bank123
    ports:
      - '4306:3306'
    volumes:
      - './mysql_data:/var/lib/mysql'

volumes:
  mysql_data:
