services:
  backend:
    build: .
    restart: always
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: '3306'
      DB_HOST: 'mysql'
    # volumes:
    #   - '.:/app-bank'
    command: sh -c "npm run build && npm run db:create && npm run db:migrate && npm run start:prod"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - './mysql_data:/var/lib/mysql'

volumes:
  mysql_data:
